### ISSUE TITLE
Nuget package not compatible with .Netstandard 1.4

### ISSUE THREAD

**Issue by marufbd** [colbylwilliams/VersionTrackingPlugin#11]
Trying to use in a .Netstandard class library as my shared code in a Xamarin project instead of PCL. Failed to install package from nuget. Would be great if made compatible with .netstandard.

**Comment by prashantvc** [comment]
There is a PR #10 to migrate the library to netstandard. I will request @colbylwilliams  to take a look at it.
Until then you can build the plugin locally with this patch
https://github.com/colbylwilliams/VersionTrackingPlugin/pull/10.patch
