### ISSUE TITLE
Not compatible with Newtonsoft.Json 10.0.3

### ISSUE THREAD

**Issue by AgustinBonilla** [colbylwilliams/VersionTrackingPlugin#14]
Unable to resolve dependencies. 'Newtonsoft.Json 10.0.3' is not compatible with 'Xam.Plugin.VersionTracking 2.0.0 constraint: Newtonsoft.Json (= 9.0.1)'.

**Comment by jamesmontemagno** [comment]
there are no dependencies: https://www.nuget.org/packages/Plugin.VersionTracking/2.0.0-beta5

**Comment by jamesmontemagno** [comment]
That is not the official plugin
