### ISSUE TITLE
Usage with XF

### ISSUE THREAD

**Issue by jerone** [colbylwilliams/VersionTrackingPlugin#16]
I have a few questions regarding initialization of this plugin with XF:

1. Should I initialize this plugin on every platform or just within XF `Application` class?
a. If initialized within XF `Application` class, should I still reference this plugin on all platfroms?
b. If initialized on every platform, should this be before or after `Forms.Init();`?
2. I see this plugin is supporting UWP; where should this be initialized on UWP?

**Comment by jamesmontemagno** [comment]
You can put it in your application class if you want to use the tracking. That would initialize on all platforms.
